apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=         # Encode : echo -n "admin" | base64 and Decode : echo -n "YWRtaW4=" | base64 --decode


